import { PracticeProblem } from "./supabase";

export const DEMO_PROBLEMS: PracticeProblem[] = [
    { id: "py-e-1", title: "Two Sum", difficulty: "Easy", language: "python", description: "Find two numbers that add up to target", examples: "", solution: "", hints: "" },
    { id: "py-e-2", title: "Reverse String", difficulty: "Easy", language: "python", description: "Reverse a string in place", examples: "", solution: "", hints: "" },
    { id: "py-e-3", title: "Palindrome Check", difficulty: "Easy", language: "python", description: "Check if a string is a palindrome", examples: "", solution: "", hints: "" },
    { id: "py-e-4", title: "FizzBuzz", difficulty: "Easy", language: "python", description: "Classic FizzBuzz problem", examples: "", solution: "", hints: "" },
    { id: "py-e-5", title: "Find Maximum", difficulty: "Easy", language: "python", description: "Find the maximum element in a list", examples: "", solution: "", hints: "" },
    { id: "py-e-6", title: "Count Vowels", difficulty: "Easy", language: "python", description: "Count vowels in a string", examples: "", solution: "", hints: "" },
    { id: "py-e-7", title: "Remove Duplicates", difficulty: "Easy", language: "python", description: "Remove duplicates from a list", examples: "", solution: "", hints: "" },
    { id: "py-e-8", title: "Sum of List", difficulty: "Easy", language: "python", description: "Calculate sum of all elements", examples: "", solution: "", hints: "" },
    { id: "py-e-9", title: "Factorial", difficulty: "Easy", language: "python", description: "Calculate factorial of a number", examples: "", solution: "", hints: "" },
    { id: "py-e-10", title: "Prime Check", difficulty: "Easy", language: "python", description: "Check if a number is prime", examples: "", solution: "", hints: "" },
    { id: "py-m-1", title: "Longest Substring", difficulty: "Medium", language: "python", description: "Find longest substring without repeating characters", examples: "", solution: "", hints: "" },
    { id: "py-m-2", title: "Valid Parentheses", difficulty: "Medium", language: "python", description: "Check if parentheses are balanced", examples: "", solution: "", hints: "" },
    { id: "py-m-3", title: "Merge Intervals", difficulty: "Medium", language: "python", description: "Merge overlapping intervals", examples: "", solution: "", hints: "" },
    { id: "py-m-4", title: "Binary Search", difficulty: "Medium", language: "python", description: "Implement binary search", examples: "", solution: "", hints: "" },
    { id: "py-m-5", title: "Group Anagrams", difficulty: "Medium", language: "python", description: "Group words that are anagrams", examples: "", solution: "", hints: "" },
    { id: "py-m-6", title: "Product of Array", difficulty: "Medium", language: "python", description: "Product of array except self", examples: "", solution: "", hints: "" },
    { id: "py-m-7", title: "Rotate Array", difficulty: "Medium", language: "python", description: "Rotate array by k steps", examples: "", solution: "", hints: "" },
    { id: "py-m-8", title: "Spiral Matrix", difficulty: "Medium", language: "python", description: "Traverse matrix in spiral order", examples: "", solution: "", hints: "" },
    { id: "py-m-9", title: "Word Search", difficulty: "Medium", language: "python", description: "Find word in a 2D grid", examples: "", solution: "", hints: "" },
    { id: "py-m-10", title: "Subsets", difficulty: "Medium", language: "python", description: "Generate all subsets", examples: "", solution: "", hints: "" },
    { id: "py-h-1", title: "Merge K Lists", difficulty: "Hard", language: "python", description: "Merge k sorted linked lists", examples: "", solution: "", hints: "" },
    { id: "py-h-2", title: "Trapping Rain Water", difficulty: "Hard", language: "python", description: "Calculate trapped rain water", examples: "", solution: "", hints: "" },
    { id: "py-h-3", title: "N-Queens", difficulty: "Hard", language: "python", description: "Solve N-Queens puzzle", examples: "", solution: "", hints: "" },
    { id: "py-h-4", title: "Word Break II", difficulty: "Hard", language: "python", description: "Find all possible sentences", examples: "", solution: "", hints: "" },
    { id: "py-h-5", title: "Median of Arrays", difficulty: "Hard", language: "python", description: "Find median of two sorted arrays", examples: "", solution: "", hints: "" },
    { id: "py-h-6", title: "Edit Distance", difficulty: "Hard", language: "python", description: "Minimum edit operations", examples: "", solution: "", hints: "" },
    { id: "py-h-7", title: "Regular Expression", difficulty: "Hard", language: "python", description: "Implement regex matching", examples: "", solution: "", hints: "" },
    { id: "py-h-8", title: "Longest Path", difficulty: "Hard", language: "python", description: "Longest increasing path in matrix", examples: "", solution: "", hints: "" },
    { id: "py-h-9", title: "Serialize Tree", difficulty: "Hard", language: "python", description: "Serialize and deserialize binary tree", examples: "", solution: "", hints: "" },
    { id: "py-h-10", title: "LRU Cache", difficulty: "Hard", language: "python", description: "Implement LRU cache", examples: "", solution: "", hints: "" },

    { id: "js-e-1", title: "Two Sum", difficulty: "Easy", language: "javascript", description: "Find two numbers that add up to target", examples: "", solution: "", hints: "" },
    { id: "js-e-2", title: "Reverse String", difficulty: "Easy", language: "javascript", description: "Reverse a string in place", examples: "", solution: "", hints: "" },
    { id: "js-e-3", title: "Palindrome Check", difficulty: "Easy", language: "javascript", description: "Check if a string is a palindrome", examples: "", solution: "", hints: "" },
    { id: "js-e-4", title: "FizzBuzz", difficulty: "Easy", language: "javascript", description: "Classic FizzBuzz problem", examples: "", solution: "", hints: "" },
    { id: "js-e-5", title: "Maximum Subarray", difficulty: "Easy", language: "javascript", description: "Find contiguous subarray with max sum", examples: "", solution: "", hints: "" },
    { id: "js-e-6", title: "Valid Anagram", difficulty: "Easy", language: "javascript", description: "Check if two strings are anagrams", examples: "", solution: "", hints: "" },
    { id: "js-e-7", title: "Merge Arrays", difficulty: "Easy", language: "javascript", description: "Merge two sorted arrays", examples: "", solution: "", hints: "" },
    { id: "js-e-8", title: "Buy Sell Stock", difficulty: "Easy", language: "javascript", description: "Best time to buy and sell stock", examples: "", solution: "", hints: "" },
    { id: "js-e-9", title: "Single Number", difficulty: "Easy", language: "javascript", description: "Find the single number", examples: "", solution: "", hints: "" },
    { id: "js-e-10", title: "Contains Duplicate", difficulty: "Easy", language: "javascript", description: "Check if array has duplicates", examples: "", solution: "", hints: "" },
    { id: "js-m-1", title: "Container With Water", difficulty: "Medium", language: "javascript", description: "Container with most water", examples: "", solution: "", hints: "" },
    { id: "js-m-2", title: "3Sum", difficulty: "Medium", language: "javascript", description: "Find three numbers that sum to zero", examples: "", solution: "", hints: "" },
    { id: "js-m-3", title: "Longest Palindrome", difficulty: "Medium", language: "javascript", description: "Find longest palindromic substring", examples: "", solution: "", hints: "" },
    { id: "js-m-4", title: "Permutations", difficulty: "Medium", language: "javascript", description: "Generate all permutations", examples: "", solution: "", hints: "" },
    { id: "js-m-5", title: "Search Rotated", difficulty: "Medium", language: "javascript", description: "Search in rotated sorted array", examples: "", solution: "", hints: "" },
    { id: "js-m-6", title: "Coin Change", difficulty: "Medium", language: "javascript", description: "Minimum coins to make amount", examples: "", solution: "", hints: "" },
    { id: "js-m-7", title: "Jump Game", difficulty: "Medium", language: "javascript", description: "Can you reach the last index", examples: "", solution: "", hints: "" },
    { id: "js-m-8", title: "Unique Paths", difficulty: "Medium", language: "javascript", description: "Count unique paths in grid", examples: "", solution: "", hints: "" },
    { id: "js-m-9", title: "Decode Ways", difficulty: "Medium", language: "javascript", description: "Count ways to decode message", examples: "", solution: "", hints: "" },
    { id: "js-m-10", title: "House Robber", difficulty: "Medium", language: "javascript", description: "Maximum money without adjacent houses", examples: "", solution: "", hints: "" },
    { id: "js-h-1", title: "Word Ladder", difficulty: "Hard", language: "javascript", description: "Shortest transformation sequence", examples: "", solution: "", hints: "" },
    { id: "js-h-2", title: "Longest Consecutive", difficulty: "Hard", language: "javascript", description: "Longest consecutive sequence", examples: "", solution: "", hints: "" },
    { id: "js-h-3", title: "Sliding Window Max", difficulty: "Hard", language: "javascript", description: "Maximum in sliding window", examples: "", solution: "", hints: "" },
    { id: "js-h-4", title: "Min Window Substr", difficulty: "Hard", language: "javascript", description: "Minimum window substring", examples: "", solution: "", hints: "" },
    { id: "js-h-5", title: "Alien Dictionary", difficulty: "Hard", language: "javascript", description: "Order of characters in alien language", examples: "", solution: "", hints: "" },
    { id: "js-h-6", title: "Maximum Profit", difficulty: "Hard", language: "javascript", description: "Best time to buy/sell with cooldown", examples: "", solution: "", hints: "" },
    { id: "js-h-7", title: "Burst Balloons", difficulty: "Hard", language: "javascript", description: "Maximum coins from bursting balloons", examples: "", solution: "", hints: "" },
    { id: "js-h-8", title: "Count Smaller", difficulty: "Hard", language: "javascript", description: "Count smaller numbers after self", examples: "", solution: "", hints: "" },
    { id: "js-h-9", title: "Remove Invalid", difficulty: "Hard", language: "javascript", description: "Remove invalid parentheses", examples: "", solution: "", hints: "" },
    { id: "js-h-10", title: "Palindrome Pairs", difficulty: "Hard", language: "javascript", description: "Find all palindrome pairs", examples: "", solution: "", hints: "" },

    { id: "ts-e-1", title: "Two Sum", difficulty: "Easy", language: "typescript", description: "Find two numbers that add up to target", examples: "", solution: "", hints: "" },
    { id: "ts-e-2", title: "Reverse String", difficulty: "Easy", language: "typescript", description: "Reverse a string in place", examples: "", solution: "", hints: "" },
    { id: "ts-e-3", title: "Valid Parentheses", difficulty: "Easy", language: "typescript", description: "Check if parentheses are balanced", examples: "", solution: "", hints: "" },
    { id: "ts-e-4", title: "Merge Arrays", difficulty: "Easy", language: "typescript", description: "Merge two sorted arrays", examples: "", solution: "", hints: "" },
    { id: "ts-e-5", title: "Roman to Integer", difficulty: "Easy", language: "typescript", description: "Convert roman numeral to integer", examples: "", solution: "", hints: "" },
    { id: "ts-e-6", title: "Longest Prefix", difficulty: "Easy", language: "typescript", description: "Find longest common prefix", examples: "", solution: "", hints: "" },
    { id: "ts-e-7", title: "Remove Element", difficulty: "Easy", language: "typescript", description: "Remove element in place", examples: "", solution: "", hints: "" },
    { id: "ts-e-8", title: "Search Insert", difficulty: "Easy", language: "typescript", description: "Find insert position", examples: "", solution: "", hints: "" },
    { id: "ts-e-9", title: "Plus One", difficulty: "Easy", language: "typescript", description: "Add one to array number", examples: "", solution: "", hints: "" },
    { id: "ts-e-10", title: "Sqrt(x)", difficulty: "Easy", language: "typescript", description: "Calculate square root", examples: "", solution: "", hints: "" },
    { id: "ts-m-1", title: "Add Two Numbers", difficulty: "Medium", language: "typescript", description: "Add two linked list numbers", examples: "", solution: "", hints: "" },
    { id: "ts-m-2", title: "String to Integer", difficulty: "Medium", language: "typescript", description: "Implement atoi", examples: "", solution: "", hints: "" },
    { id: "ts-m-3", title: "Zigzag Conversion", difficulty: "Medium", language: "typescript", description: "Zigzag pattern string", examples: "", solution: "", hints: "" },
    { id: "ts-m-4", title: "Integer to Roman", difficulty: "Medium", language: "typescript", description: "Convert integer to roman", examples: "", solution: "", hints: "" },
    { id: "ts-m-5", title: "Letter Combinations", difficulty: "Medium", language: "typescript", description: "Phone number letter combinations", examples: "", solution: "", hints: "" },
    { id: "ts-m-6", title: "Generate Parens", difficulty: "Medium", language: "typescript", description: "Generate valid parentheses", examples: "", solution: "", hints: "" },
    { id: "ts-m-7", title: "Next Permutation", difficulty: "Medium", language: "typescript", description: "Find next permutation", examples: "", solution: "", hints: "" },
    { id: "ts-m-8", title: "Combination Sum", difficulty: "Medium", language: "typescript", description: "Find combinations that sum to target", examples: "", solution: "", hints: "" },
    { id: "ts-m-9", title: "Pow(x, n)", difficulty: "Medium", language: "typescript", description: "Implement power function", examples: "", solution: "", hints: "" },
    { id: "ts-m-10", title: "Maximum Product", difficulty: "Medium", language: "typescript", description: "Maximum product subarray", examples: "", solution: "", hints: "" },
    { id: "ts-h-1", title: "First Missing", difficulty: "Hard", language: "typescript", description: "First missing positive", examples: "", solution: "", hints: "" },
    { id: "ts-h-2", title: "Wildcard Match", difficulty: "Hard", language: "typescript", description: "Wildcard pattern matching", examples: "", solution: "", hints: "" },
    { id: "ts-h-3", title: "Jump Game II", difficulty: "Hard", language: "typescript", description: "Minimum jumps to reach end", examples: "", solution: "", hints: "" },
    { id: "ts-h-4", title: "Insert Interval", difficulty: "Hard", language: "typescript", description: "Insert and merge intervals", examples: "", solution: "", hints: "" },
    { id: "ts-h-5", title: "Text Justify", difficulty: "Hard", language: "typescript", description: "Justify text into lines", examples: "", solution: "", hints: "" },
    { id: "ts-h-6", title: "Largest Rectangle", difficulty: "Hard", language: "typescript", description: "Largest rectangle in histogram", examples: "", solution: "", hints: "" },
    { id: "ts-h-7", title: "Scramble String", difficulty: "Hard", language: "typescript", description: "Check if scrambled string", examples: "", solution: "", hints: "" },
    { id: "ts-h-8", title: "Interleaving String", difficulty: "Hard", language: "typescript", description: "Check if interleaving", examples: "", solution: "", hints: "" },
    { id: "ts-h-9", title: "Distinct Subseq", difficulty: "Hard", language: "typescript", description: "Count distinct subsequences", examples: "", solution: "", hints: "" },
    { id: "ts-h-10", title: "Max Points Line", difficulty: "Hard", language: "typescript", description: "Max points on a line", examples: "", solution: "", hints: "" },

    { id: "java-e-1", title: "Two Sum", difficulty: "Easy", language: "java", description: "Find two numbers that add up to target", examples: "", solution: "", hints: "" },
    { id: "java-e-2", title: "Reverse String", difficulty: "Easy", language: "java", description: "Reverse a string", examples: "", solution: "", hints: "" },
    { id: "java-e-3", title: "Palindrome Number", difficulty: "Easy", language: "java", description: "Check if number is palindrome", examples: "", solution: "", hints: "" },
    { id: "java-e-4", title: "Valid Parentheses", difficulty: "Easy", language: "java", description: "Check balanced parentheses", examples: "", solution: "", hints: "" },
    { id: "java-e-5", title: "Merge Lists", difficulty: "Easy", language: "java", description: "Merge two sorted lists", examples: "", solution: "", hints: "" },
    { id: "java-e-6", title: "Climbing Stairs", difficulty: "Easy", language: "java", description: "Ways to climb n stairs", examples: "", solution: "", hints: "" },
    { id: "java-e-7", title: "Same Tree", difficulty: "Easy", language: "java", description: "Check if trees are same", examples: "", solution: "", hints: "" },
    { id: "java-e-8", title: "Symmetric Tree", difficulty: "Easy", language: "java", description: "Check if tree is symmetric", examples: "", solution: "", hints: "" },
    { id: "java-e-9", title: "Max Depth Tree", difficulty: "Easy", language: "java", description: "Maximum depth of binary tree", examples: "", solution: "", hints: "" },
    { id: "java-e-10", title: "Path Sum", difficulty: "Easy", language: "java", description: "Check if path sum exists", examples: "", solution: "", hints: "" },
    { id: "java-m-1", title: "Add Two Numbers", difficulty: "Medium", language: "java", description: "Add linked list numbers", examples: "", solution: "", hints: "" },
    { id: "java-m-2", title: "Longest Substring", difficulty: "Medium", language: "java", description: "Longest substring without repeat", examples: "", solution: "", hints: "" },
    { id: "java-m-3", title: "Reverse Integer", difficulty: "Medium", language: "java", description: "Reverse digits of integer", examples: "", solution: "", hints: "" },
    { id: "java-m-4", title: "Container Water", difficulty: "Medium", language: "java", description: "Most water container can hold", examples: "", solution: "", hints: "" },
    { id: "java-m-5", title: "3Sum", difficulty: "Medium", language: "java", description: "Three numbers sum to zero", examples: "", solution: "", hints: "" },
    { id: "java-m-6", title: "4Sum", difficulty: "Medium", language: "java", description: "Four numbers sum to target", examples: "", solution: "", hints: "" },
    { id: "java-m-7", title: "Remove Nth Node", difficulty: "Medium", language: "java", description: "Remove nth node from end", examples: "", solution: "", hints: "" },
    { id: "java-m-8", title: "Swap Pairs", difficulty: "Medium", language: "java", description: "Swap every two nodes", examples: "", solution: "", hints: "" },
    { id: "java-m-9", title: "Rotate List", difficulty: "Medium", language: "java", description: "Rotate list by k places", examples: "", solution: "", hints: "" },
    { id: "java-m-10", title: "Sort Colors", difficulty: "Medium", language: "java", description: "Sort colors (Dutch flag)", examples: "", solution: "", hints: "" },
    { id: "java-h-1", title: "Median Arrays", difficulty: "Hard", language: "java", description: "Median of two sorted arrays", examples: "", solution: "", hints: "" },
    { id: "java-h-2", title: "Merge K Lists", difficulty: "Hard", language: "java", description: "Merge k sorted lists", examples: "", solution: "", hints: "" },
    { id: "java-h-3", title: "Reverse K Group", difficulty: "Hard", language: "java", description: "Reverse nodes in k-group", examples: "", solution: "", hints: "" },
    { id: "java-h-4", title: "Substring Concat", difficulty: "Hard", language: "java", description: "Substring with concatenation", examples: "", solution: "", hints: "" },
    { id: "java-h-5", title: "Sudoku Solver", difficulty: "Hard", language: "java", description: "Solve sudoku puzzle", examples: "", solution: "", hints: "" },
    { id: "java-h-6", title: "N-Queens II", difficulty: "Hard", language: "java", description: "Count N-Queens solutions", examples: "", solution: "", hints: "" },
    { id: "java-h-7", title: "Permutations II", difficulty: "Hard", language: "java", description: "Permutations with duplicates", examples: "", solution: "", hints: "" },
    { id: "java-h-8", title: "Maximal Rectangle", difficulty: "Hard", language: "java", description: "Largest rectangle in matrix", examples: "", solution: "", hints: "" },
    { id: "java-h-9", title: "Recover BST", difficulty: "Hard", language: "java", description: "Recover binary search tree", examples: "", solution: "", hints: "" },
    { id: "java-h-10", title: "Word Search II", difficulty: "Hard", language: "java", description: "Find words in 2D board", examples: "", solution: "", hints: "" },

    { id: "c-e-1", title: "Two Sum", difficulty: "Easy", language: "c", description: "Find two numbers that add to target", examples: "", solution: "", hints: "" },
    { id: "c-e-2", title: "Reverse Array", difficulty: "Easy", language: "c", description: "Reverse array in place using pointers", examples: "", solution: "", hints: "" },
    { id: "c-e-3", title: "String Length", difficulty: "Easy", language: "c", description: "Implement strlen without library", examples: "", solution: "", hints: "" },
    { id: "c-e-4", title: "Swap Numbers", difficulty: "Easy", language: "c", description: "Swap two numbers using pointers", examples: "", solution: "", hints: "" },
    { id: "c-e-5", title: "Binary Search", difficulty: "Easy", language: "c", description: "Implement binary search", examples: "", solution: "", hints: "" },
    { id: "c-e-6", title: "Palindrome Check", difficulty: "Easy", language: "c", description: "Check if string is palindrome", examples: "", solution: "", hints: "" },
    { id: "c-e-7", title: "Find Maximum", difficulty: "Easy", language: "c", description: "Find max element in array", examples: "", solution: "", hints: "" },
    { id: "c-e-8", title: "Count Digits", difficulty: "Easy", language: "c", description: "Count digits in a number", examples: "", solution: "", hints: "" },
    { id: "c-e-9", title: "Factorial", difficulty: "Easy", language: "c", description: "Calculate factorial iteratively", examples: "", solution: "", hints: "" },
    { id: "c-e-10", title: "Prime Check", difficulty: "Easy", language: "c", description: "Check if number is prime", examples: "", solution: "", hints: "" },
    { id: "c-m-1", title: "Merge Sort", difficulty: "Medium", language: "c", description: "Implement merge sort algorithm", examples: "", solution: "", hints: "" },
    { id: "c-m-2", title: "Quick Sort", difficulty: "Medium", language: "c", description: "Implement quicksort algorithm", examples: "", solution: "", hints: "" },
    { id: "c-m-3", title: "Linked List", difficulty: "Medium", language: "c", description: "Implement singly linked list", examples: "", solution: "", hints: "" },
    { id: "c-m-4", title: "Stack with Array", difficulty: "Medium", language: "c", description: "Implement stack using arrays", examples: "", solution: "", hints: "" },
    { id: "c-m-5", title: "Queue with Array", difficulty: "Medium", language: "c", description: "Implement queue using arrays", examples: "", solution: "", hints: "" },
    { id: "c-m-6", title: "Dynamic Array", difficulty: "Medium", language: "c", description: "Implement resizable array", examples: "", solution: "", hints: "" },
    { id: "c-m-7", title: "String Concat", difficulty: "Medium", language: "c", description: "Concatenate strings with malloc", examples: "", solution: "", hints: "" },
    { id: "c-m-8", title: "Matrix Multiply", difficulty: "Medium", language: "c", description: "Multiply two matrices", examples: "", solution: "", hints: "" },
    { id: "c-m-9", title: "Binary Tree", difficulty: "Medium", language: "c", description: "Implement binary tree operations", examples: "", solution: "", hints: "" },
    { id: "c-m-10", title: "Hash Table", difficulty: "Medium", language: "c", description: "Implement simple hash table", examples: "", solution: "", hints: "" },
    { id: "c-h-1", title: "Memory Pool", difficulty: "Hard", language: "c", description: "Implement custom memory allocator", examples: "", solution: "", hints: "" },
    { id: "c-h-2", title: "Red-Black Tree", difficulty: "Hard", language: "c", description: "Implement red-black tree", examples: "", solution: "", hints: "" },
    { id: "c-h-3", title: "Graph BFS/DFS", difficulty: "Hard", language: "c", description: "Graph traversal algorithms", examples: "", solution: "", hints: "" },
    { id: "c-h-4", title: "Dijkstra", difficulty: "Hard", language: "c", description: "Shortest path algorithm", examples: "", solution: "", hints: "" },
    { id: "c-h-5", title: "AVL Tree", difficulty: "Hard", language: "c", description: "Self-balancing binary tree", examples: "", solution: "", hints: "" },
    { id: "c-h-6", title: "Heap Sort", difficulty: "Hard", language: "c", description: "Implement heap sort", examples: "", solution: "", hints: "" },
    { id: "c-h-7", title: "LRU Cache", difficulty: "Hard", language: "c", description: "Implement LRU cache with pointers", examples: "", solution: "", hints: "" },
    { id: "c-h-8", title: "Trie", difficulty: "Hard", language: "c", description: "Implement trie data structure", examples: "", solution: "", hints: "" },
    { id: "c-h-9", title: "Thread Pool", difficulty: "Hard", language: "c", description: "Implement thread pool", examples: "", solution: "", hints: "" },
    { id: "c-h-10", title: "File System", difficulty: "Hard", language: "c", description: "Simple file system simulation", examples: "", solution: "", hints: "" },

    { id: "cpp-e-1", title: "Two Sum", difficulty: "Easy", language: "cpp", description: "Find two numbers that add to target", examples: "", solution: "", hints: "" },
    { id: "cpp-e-2", title: "Reverse String", difficulty: "Easy", language: "cpp", description: "Reverse string using STL", examples: "", solution: "", hints: "" },
    { id: "cpp-e-3", title: "Palindrome Check", difficulty: "Easy", language: "cpp", description: "Check if string is palindrome", examples: "", solution: "", hints: "" },
    { id: "cpp-e-4", title: "FizzBuzz", difficulty: "Easy", language: "cpp", description: "Classic FizzBuzz with streams", examples: "", solution: "", hints: "" },
    { id: "cpp-e-5", title: "Vector Operations", difficulty: "Easy", language: "cpp", description: "Basic vector manipulations", examples: "", solution: "", hints: "" },
    { id: "cpp-e-6", title: "Map Usage", difficulty: "Easy", language: "cpp", description: "Using std::map effectively", examples: "", solution: "", hints: "" },
    { id: "cpp-e-7", title: "Set Operations", difficulty: "Easy", language: "cpp", description: "Working with std::set", examples: "", solution: "", hints: "" },
    { id: "cpp-e-8", title: "String Stream", difficulty: "Easy", language: "cpp", description: "Parse strings with stringstream", examples: "", solution: "", hints: "" },
    { id: "cpp-e-9", title: "Find in Array", difficulty: "Easy", language: "cpp", description: "Use STL algorithms to search", examples: "", solution: "", hints: "" },
    { id: "cpp-e-10", title: "Sort Custom", difficulty: "Easy", language: "cpp", description: "Custom comparator sorting", examples: "", solution: "", hints: "" },
    { id: "cpp-m-1", title: "Smart Pointers", difficulty: "Medium", language: "cpp", description: "Implement using unique_ptr", examples: "", solution: "", hints: "" },
    { id: "cpp-m-2", title: "Lambda Functions", difficulty: "Medium", language: "cpp", description: "Advanced lambda usage", examples: "", solution: "", hints: "" },
    { id: "cpp-m-3", title: "Template Class", difficulty: "Medium", language: "cpp", description: "Create a template container", examples: "", solution: "", hints: "" },
    { id: "cpp-m-4", title: "Move Semantics", difficulty: "Medium", language: "cpp", description: "Implement move constructor", examples: "", solution: "", hints: "" },
    { id: "cpp-m-5", title: "Iterator", difficulty: "Medium", language: "cpp", description: "Custom iterator implementation", examples: "", solution: "", hints: "" },
    { id: "cpp-m-6", title: "RAII Pattern", difficulty: "Medium", language: "cpp", description: "Resource management pattern", examples: "", solution: "", hints: "" },
    { id: "cpp-m-7", title: "Operator Overload", difficulty: "Medium", language: "cpp", description: "Overload common operators", examples: "", solution: "", hints: "" },
    { id: "cpp-m-8", title: "Exception Safe", difficulty: "Medium", language: "cpp", description: "Exception-safe code", examples: "", solution: "", hints: "" },
    { id: "cpp-m-9", title: "Thread Basic", difficulty: "Medium", language: "cpp", description: "Basic multithreading", examples: "", solution: "", hints: "" },
    { id: "cpp-m-10", title: "Mutex Usage", difficulty: "Medium", language: "cpp", description: "Synchronization with mutex", examples: "", solution: "", hints: "" },
    { id: "cpp-h-1", title: "Memory Pool", difficulty: "Hard", language: "cpp", description: "Custom allocator implementation", examples: "", solution: "", hints: "" },
    { id: "cpp-h-2", title: "Lock-Free Queue", difficulty: "Hard", language: "cpp", description: "Atomic-based queue", examples: "", solution: "", hints: "" },
    { id: "cpp-h-3", title: "Expression Parser", difficulty: "Hard", language: "cpp", description: "Parse and evaluate expressions", examples: "", solution: "", hints: "" },
    { id: "cpp-h-4", title: "Graph Algorithms", difficulty: "Hard", language: "cpp", description: "Advanced graph operations", examples: "", solution: "", hints: "" },
    { id: "cpp-h-5", title: "Coroutines", difficulty: "Hard", language: "cpp", description: "C++20 coroutines usage", examples: "", solution: "", hints: "" },
    { id: "cpp-h-6", title: "Type Erasure", difficulty: "Hard", language: "cpp", description: "Implement type erasure", examples: "", solution: "", hints: "" },
    { id: "cpp-h-7", title: "Compile Time", difficulty: "Hard", language: "cpp", description: "constexpr computations", examples: "", solution: "", hints: "" },
    { id: "cpp-h-8", title: "Variadic Templates", difficulty: "Hard", language: "cpp", description: "Advanced template metaprogramming", examples: "", solution: "", hints: "" },
    { id: "cpp-h-9", title: "Concepts", difficulty: "Hard", language: "cpp", description: "C++20 concepts usage", examples: "", solution: "", hints: "" },
    { id: "cpp-h-10", title: "Ranges Library", difficulty: "Hard", language: "cpp", description: "Advanced ranges operations", examples: "", solution: "", hints: "" },

    // HTML
    { id: "html-e-1", title: "Basic Structure", difficulty: "Easy", language: "html", description: "Create a basic HTML page structure", examples: "", solution: "", hints: "" },
    { id: "html-m-1", title: "Semantic Tags", difficulty: "Medium", language: "html", description: "Use semantic tags correctly", examples: "", solution: "", hints: "" },

    // CSS
    { id: "css-e-1", title: "Color & Fonts", difficulty: "Easy", language: "css", description: "Change text color and font family", examples: "", solution: "", hints: "" },
    { id: "css-m-1", title: "Flexbox Center", difficulty: "Medium", language: "css", description: "Center an element using Flexbox", examples: "", solution: "", hints: "" },

    // PHP
    { id: "php-e-1", title: "Hello World", difficulty: "Easy", language: "php", description: "Print Hello World in PHP", examples: "", solution: "", hints: "" },
    { id: "php-m-1", title: "Array Filter", difficulty: "Medium", language: "php", description: "Filter an array based on condition", examples: "", solution: "", hints: "" },

    // Ruby
    { id: "ruby-e-1", title: "String Interpolation", difficulty: "Easy", language: "ruby", description: "Use string interpolation", examples: "", solution: "", hints: "" },
    { id: "ruby-m-1", title: "Blocks", difficulty: "Medium", language: "ruby", description: "Create a method that accepts a block", examples: "", solution: "", hints: "" },

    // SQL
    { id: "sql-e-1", title: "Select All", difficulty: "Easy", language: "sql", description: "Select all columns from a table", examples: "", solution: "", hints: "" },
    { id: "sql-m-1", title: "Group By", difficulty: "Medium", language: "sql", description: "Group results and count", examples: "", solution: "", hints: "" },

    // Swift
    { id: "swift-e-1", title: "Variables", difficulty: "Easy", language: "swift", description: "Declare constants and variables", examples: "", solution: "", hints: "" },
    { id: "swift-m-1", title: "Closures", difficulty: "Medium", language: "swift", description: "Write a simple closure", examples: "", solution: "", hints: "" },

    // Kotlin
    { id: "kotlin-e-1", title: "Null Safety", difficulty: "Easy", language: "kotlin", description: "Handle nullable types", examples: "", solution: "", hints: "" },
    { id: "kotlin-m-1", title: "Data Classes", difficulty: "Medium", language: "kotlin", description: "Create a data class", examples: "", solution: "", hints: "" },

    // Dart
    { id: "dart-e-1", title: "Functions", difficulty: "Easy", language: "dart", description: "Write a simple function", examples: "", solution: "", hints: "" },
    { id: "dart-m-1", title: "Streams", difficulty: "Medium", language: "dart", description: "Create a simple stream", examples: "", solution: "", hints: "" },

    // C#
    { id: "csharp-e-1", title: "Properties", difficulty: "Easy", language: "csharp", description: "Use auto-implemented properties", examples: "", solution: "", hints: "" },
    { id: "csharp-m-1", title: "LINQ Select", difficulty: "Medium", language: "csharp", description: "Select specific fields using LINQ", examples: "", solution: "", hints: "" },

    // Go
    { id: "go-e-1", title: "Slices", difficulty: "Easy", language: "go", description: "Work with slices", examples: "", solution: "", hints: "" },
    { id: "go-m-1", title: "Channels", difficulty: "Medium", language: "go", description: "Send data through a channel", examples: "", solution: "", hints: "" },

    // Rust
    { id: "rust-e-1", title: "Ownership", difficulty: "Easy", language: "rust", description: "Demonstrate ownership rules", examples: "", solution: "", hints: "" },
    { id: "rust-m-1", title: "Result Type", difficulty: "Medium", language: "rust", description: "Handle errors with Result", examples: "", solution: "", hints: "" },

    // R
    { id: "r-e-1", title: "Vectors", difficulty: "Easy", language: "r", description: "Create and manipulate vectors", examples: "", solution: "", hints: "" },
    { id: "r-m-1", title: "Data Frames", difficulty: "Medium", language: "r", description: "Filter a data frame", examples: "", solution: "", hints: "" },

    // Julia
    { id: "julia-e-1", title: "Functions", difficulty: "Easy", language: "julia", description: "Define a function", examples: "", solution: "", hints: "" },
    { id: "julia-m-1", title: "Multiple Dispatch", difficulty: "Medium", language: "julia", description: "Demonstrate multiple dispatch", examples: "", solution: "", hints: "" },

    // Scala
    { id: "scala-e-1", title: "Pattern Matching", difficulty: "Easy", language: "scala", description: "Use pattern matching", examples: "", solution: "", hints: "" },
    { id: "scala-m-1", title: "Case Classes", difficulty: "Medium", language: "scala", description: "Define a case class", examples: "", solution: "", hints: "" },
];
